### ISSUE TITLE
Uncaught Error: Cannot find module 'es6-tween'

### ISSUE THREAD

**Issue by RanggaPAji** [diegodorado/atom-live-emojing#1]
Hi Diego! i just stumbled on your `live-emojing` for live coding technique on your Github, and i was thinking about trying it out. So I tried to install the `live-emojing` from Atom, but after the installation i got this instead.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [live-emojing](https://github.com/diegodorado/atom-live-emojing) package 0.1.1

### Stack Trace

Uncaught Error: Cannot find module 'es6-tween'

```
At module.js:545

Error: Cannot find module 'es6-tween'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:154765)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146072)
    at /packages/live-emojing/lib/webgl/scene.js:11:17)
    at /packages/live-emojing/lib/webgl/scene.js:22:31)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146072)
    at /packages/live-emojing/lib/live-emojing-view.js:11:19)
    at /packages/live-emojing/lib/live-emojing-view.js:5:37)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146072)
    at /packages/live-emojing/lib/live-emojing.js:9:24)
    at /packages/live-emojing/lib/live-emojing.js:341:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

### Commands

```
     -2:45.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-hydra 0.2.10 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autocomplete-glsl 0.2.3 
busy-signal 2.0.1 
foxdot 1.0.0 
framer-syntax 1.1.0 
framer-ui 2.0.0 
GobbieGobGoo 1.0.4 
handsome-light-syntax 0.3.4 
intentions 1.1.5 
language-glsl 2.0.4 
linter 2.3.0 
linter-glsl 2.2.0 
linter-ui-default 1.7.1 
live-emojing 0.1.1 
monokai 0.24.0 
moonlight 0.11.0 
teletype 0.13.3 
tidalcycles 0.15.0 
veda 2.11.4 
```

**Comment by diegodorado** [comment]
Hi @RanggaPAji , thanks for the report. I would need two more days to update this repository since it had many changes, but I am pretty close. I will update this issue when I am finished with it

**Comment by RanggaPAji** [comment]
Allright diego thank you so much, goodluck and all the best!

**Comment by diegodorado** [comment]
Can you try again with the new version? Thanks

**Comment by RanggaPAji** [comment]
Hi Diego!

Yes it's showing the live-emojing interface now, but i couldn't do the
control+shift+E for the activation of the emoji's region. I'm using
MacBook, is there another way for it? or maybe i'm missing something?

**Comment by diegodorado** [comment]
Try through the menu. Packages - live emojing- bind

**Comment by diegodorado** [comment]
Maybe it is cmd shift E on OSX?

**Comment by RanggaPAji** [comment]
Yes it's supposed to be cmd+shift+E but still won't work. Do i need to
prepare another thing first before it?

**Comment by diegodorado** [comment]
But if you go through the menu it doesn't do anything or do you get an
error?

**Comment by RanggaPAji** [comment]
It doesn't do anything, i did as the instruction instruct me to do.
